### ISSUE TITLE
UI Enhancement - Improving the button in the hover

### ISSUE THREAD

**Issue by anshulsoni2010** [preetsuthar17/HextaUI#2]
Current button in navigation bar is not looking cool according to the current motive of the website. And, as the current motive of the HextaUI Components is to provide good ui components for developer to code faster on their client project instead of making the components design from scratch. and taking that in mind, I thought to have a good design of that button.
You can assign me on this mini issue but yupp, I would be doing more later on as it takes time to see what can be improved and as this OS so no worries about these things.

![image](https://github.com/preetsuthar17/HextaUI/assets/102960277/a02822ab-a7c7-4684-993a-220e91113ff8)

Assign me so I will send some example screenshot of how that will look. 

Thank you @preetsuthar17 
-- Anshul Soni

**Comment by preetsuthar17** [comment]
HextaUI is open source mate! feel free to make your pull request!
