### ISSUE TITLE
UI Enhancement - Adding Custom Scrollbar in Y Axis

### ISSUE THREAD

**Issue by anshulsoni2010** [preetsuthar17/HextaUI#4]
There should be the custom vertical scrollbar with the cool color pallets according to the theme.

Assign Me So I will work on it...

**Comment by preetsuthar17** [comment]
@anshulsoni2010 Done!

**Comment by anshulsoni2010** [comment]
Sure, Am Working

**Comment by anshulsoni2010** [comment]
PR Raised at #5
